python paramSweepVideo_gaussian_check.py 3 1.0
python paramSweepVideo_gaussian_check.py 3 1.5
python paramSweepVideo_gaussian_check.py 3 2.0
python paramSweepVideo_gaussian_check.py 3 2.5
python paramSweepVideo_gaussian_check.py 3 3.0
python paramSweepVideo_gaussian_check.py 3 3.5
python paramSweepVideo_gaussian_check.py 3 4.0
python paramSweepVideo_gaussian_check.py 3 4.5
python paramSweepVideo_gaussian_check.py 3 5.0
python paramSweepVideo_gaussian_check.py 3 5.5
python paramSweepVideo_gaussian_check.py 3 6.0
python paramSweepVideo_gaussian_check.py 3 6.5
python paramSweepVideo_gaussian_check.py 3 7.0
python paramSweepVideo_gaussian_check.py 3 7.5
python paramSweepVideo_gaussian_check.py 3 8.0
python paramSweepVideo_gaussian_check.py 3 8.5
python paramSweepVideo_gaussian_check.py 3 9.0
python paramSweepVideo_gaussian_check.py 3 9.5
python paramSweepVideo_gaussian_check.py 5 1.0
python paramSweepVideo_gaussian_check.py 5 1.5
python paramSweepVideo_gaussian_check.py 5 2.0
python paramSweepVideo_gaussian_check.py 5 2.5
python paramSweepVideo_gaussian_check.py 5 3.0
python paramSweepVideo_gaussian_check.py 5 3.5
python paramSweepVideo_gaussian_check.py 5 4.0
python paramSweepVideo_gaussian_check.py 5 4.5
python paramSweepVideo_gaussian_check.py 5 5.0
python paramSweepVideo_gaussian_check.py 5 5.5
python paramSweepVideo_gaussian_check.py 5 6.0
python paramSweepVideo_gaussian_check.py 5 6.5
python paramSweepVideo_gaussian_check.py 5 7.0
python paramSweepVideo_gaussian_check.py 5 7.5
python paramSweepVideo_gaussian_check.py 5 8.0
python paramSweepVideo_gaussian_check.py 5 8.5
python paramSweepVideo_gaussian_check.py 5 9.0
python paramSweepVideo_gaussian_check.py 5 9.5
python paramSweepVideo_gaussian_check.py 7 1.0
python paramSweepVideo_gaussian_check.py 7 1.5
python paramSweepVideo_gaussian_check.py 7 2.0
python paramSweepVideo_gaussian_check.py 7 2.5
python paramSweepVideo_gaussian_check.py 7 3.0
python paramSweepVideo_gaussian_check.py 7 3.5
python paramSweepVideo_gaussian_check.py 7 4.0
python paramSweepVideo_gaussian_check.py 7 4.5
python paramSweepVideo_gaussian_check.py 7 5.0
python paramSweepVideo_gaussian_check.py 7 5.5
python paramSweepVideo_gaussian_check.py 7 6.0
python paramSweepVideo_gaussian_check.py 7 6.5
python paramSweepVideo_gaussian_check.py 7 7.0
python paramSweepVideo_gaussian_check.py 7 7.5
python paramSweepVideo_gaussian_check.py 7 8.0
python paramSweepVideo_gaussian_check.py 7 8.5
python paramSweepVideo_gaussian_check.py 7 9.0
python paramSweepVideo_gaussian_check.py 7 9.5
python paramSweepVideo_gaussian_check.py 9 1.0
python paramSweepVideo_gaussian_check.py 9 1.5
python paramSweepVideo_gaussian_check.py 9 2.0
python paramSweepVideo_gaussian_check.py 9 2.5
python paramSweepVideo_gaussian_check.py 9 3.0
python paramSweepVideo_gaussian_check.py 9 3.5
python paramSweepVideo_gaussian_check.py 9 4.0
python paramSweepVideo_gaussian_check.py 9 4.5
python paramSweepVideo_gaussian_check.py 9 5.0
python paramSweepVideo_gaussian_check.py 9 5.5
python paramSweepVideo_gaussian_check.py 9 6.0
python paramSweepVideo_gaussian_check.py 9 6.5
python paramSweepVideo_gaussian_check.py 9 7.0
python paramSweepVideo_gaussian_check.py 9 7.5
python paramSweepVideo_gaussian_check.py 9 8.0
python paramSweepVideo_gaussian_check.py 9 8.5
python paramSweepVideo_gaussian_check.py 9 9.0
python paramSweepVideo_gaussian_check.py 9 9.5
python paramSweepVideo_gaussian_check.py 11 1.0
python paramSweepVideo_gaussian_check.py 11 1.5
python paramSweepVideo_gaussian_check.py 11 2.0
python paramSweepVideo_gaussian_check.py 11 2.5
python paramSweepVideo_gaussian_check.py 11 3.0
python paramSweepVideo_gaussian_check.py 11 3.5
python paramSweepVideo_gaussian_check.py 11 4.0
python paramSweepVideo_gaussian_check.py 11 4.5
python paramSweepVideo_gaussian_check.py 11 5.0
python paramSweepVideo_gaussian_check.py 11 5.5
python paramSweepVideo_gaussian_check.py 11 6.0
python paramSweepVideo_gaussian_check.py 11 6.5
python paramSweepVideo_gaussian_check.py 11 7.0
python paramSweepVideo_gaussian_check.py 11 7.5
python paramSweepVideo_gaussian_check.py 11 8.0
python paramSweepVideo_gaussian_check.py 11 8.5
python paramSweepVideo_gaussian_check.py 11 9.0
python paramSweepVideo_gaussian_check.py 11 9.5
python paramSweepVideo_gaussian_check.py 13 1.0
python paramSweepVideo_gaussian_check.py 13 1.5
python paramSweepVideo_gaussian_check.py 13 2.0
python paramSweepVideo_gaussian_check.py 13 2.5
python paramSweepVideo_gaussian_check.py 13 3.0
python paramSweepVideo_gaussian_check.py 13 3.5
python paramSweepVideo_gaussian_check.py 13 4.0
python paramSweepVideo_gaussian_check.py 13 4.5
python paramSweepVideo_gaussian_check.py 13 5.0
python paramSweepVideo_gaussian_check.py 13 5.5
python paramSweepVideo_gaussian_check.py 13 6.0
python paramSweepVideo_gaussian_check.py 13 6.5
python paramSweepVideo_gaussian_check.py 13 7.0
python paramSweepVideo_gaussian_check.py 13 7.5
python paramSweepVideo_gaussian_check.py 13 8.0
python paramSweepVideo_gaussian_check.py 13 8.5
python paramSweepVideo_gaussian_check.py 13 9.0
python paramSweepVideo_gaussian_check.py 13 9.5
