python paramSweepVideo_gaussian_check.py 3 7.5
python paramSweepVideo_gaussian_check.py 3 8.0
python paramSweepVideo_gaussian_check.py 3 8.5
python paramSweepVideo_gaussian_check.py 3 9.0
python paramSweepVideo_gaussian_check.py 3 9.5
python paramSweepVideo_gaussian_check.py 3 10.0
python paramSweepVideo_gaussian_check.py 5 7.5
python paramSweepVideo_gaussian_check.py 5 8.0
python paramSweepVideo_gaussian_check.py 5 8.5
python paramSweepVideo_gaussian_check.py 5 9.0
python paramSweepVideo_gaussian_check.py 5 9.5
python paramSweepVideo_gaussian_check.py 5 10.0
python paramSweepVideo_gaussian_check.py 7 7.5
python paramSweepVideo_gaussian_check.py 7 8.0
python paramSweepVideo_gaussian_check.py 7 8.5
python paramSweepVideo_gaussian_check.py 7 9.0
python paramSweepVideo_gaussian_check.py 7 9.5
python paramSweepVideo_gaussian_check.py 7 10.0
python paramSweepVideo_gaussian_check.py 9 7.5
python paramSweepVideo_gaussian_check.py 9 8.0
python paramSweepVideo_gaussian_check.py 9 8.5
python paramSweepVideo_gaussian_check.py 9 9.0
python paramSweepVideo_gaussian_check.py 9 9.5
python paramSweepVideo_gaussian_check.py 9 10.0
python paramSweepVideo_gaussian_check.py 11 7.5
python paramSweepVideo_gaussian_check.py 11 8.0
python paramSweepVideo_gaussian_check.py 11 8.5
python paramSweepVideo_gaussian_check.py 11 9.0
python paramSweepVideo_gaussian_check.py 11 9.5
python paramSweepVideo_gaussian_check.py 11 10.0
python paramSweepVideo_gaussian_check.py 13 7.5
python paramSweepVideo_gaussian_check.py 13 8.0
python paramSweepVideo_gaussian_check.py 13 8.5
python paramSweepVideo_gaussian_check.py 13 9.0
python paramSweepVideo_gaussian_check.py 13 9.5
python paramSweepVideo_gaussian_check.py 13 10.0
